// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ_gS5lsfZEBIIHTaxeH_LnP59QVZ4jRw',
    appId: '1:363967512932:web:49e5c355f2a3c85a263a71',
    messagingSenderId: '363967512932',
    projectId: 'sistemaescolar-76ba6',
    authDomain: 'sistemaescolar-76ba6.firebaseapp.com',
    storageBucket: 'sistemaescolar-76ba6.firebasestorage.app',
    measurementId: 'G-85F6SHXJLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMsuAOOL7oYkVa_OXiMqgZeLKqTbEx7zc',
    appId: '1:363967512932:android:a721672a628aa5e0263a71',
    messagingSenderId: '363967512932',
    projectId: 'sistemaescolar-76ba6',
    storageBucket: 'sistemaescolar-76ba6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhFYsuJ23aJ8jfyDRaGLAmj5uXVrY44uw',
    appId: '1:363967512932:ios:22d0f0f2876bc095263a71',
    messagingSenderId: '363967512932',
    projectId: 'sistemaescolar-76ba6',
    storageBucket: 'sistemaescolar-76ba6.firebasestorage.app',
    iosBundleId: 'com.example.job',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhFYsuJ23aJ8jfyDRaGLAmj5uXVrY44uw',
    appId: '1:363967512932:ios:22d0f0f2876bc095263a71',
    messagingSenderId: '363967512932',
    projectId: 'sistemaescolar-76ba6',
    storageBucket: 'sistemaescolar-76ba6.firebasestorage.app',
    iosBundleId: 'com.example.job',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ_gS5lsfZEBIIHTaxeH_LnP59QVZ4jRw',
    appId: '1:363967512932:web:f30aabfc69b510e3263a71',
    messagingSenderId: '363967512932',
    projectId: 'sistemaescolar-76ba6',
    authDomain: 'sistemaescolar-76ba6.firebaseapp.com',
    storageBucket: 'sistemaescolar-76ba6.firebasestorage.app',
    measurementId: 'G-YKTXVFCB8L',
  );

}